version: '3.6'
services:
    postgresql:
        image: postgres:10.6
        volumes:
        - aip-data:/var/lib/postgresql/data
        environment:
        - POSTGRES_USER=operator
        - POSTGRES_PASSWORD=CastAIP
        - POSTGRES_DB=postgres
        - PGDATA=/var/lib/postgresql/data/pgdata
        command: "-N 300 -c 'temp_buffers=32MB' -c 'work_mem=64MB' -c 'maintenance_work_mem=1024MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'commit_delay=10' -c 'checkpoint_completion_target=0.9' -c 'cursor_tuple_fraction=1.0' -c 'log_checkpoints=on' -c 'log_destination=stderr' -c 'logging_collector=on' -c 'log_line_prefix=%t [%p]: [%l-1] ' -c 'log_temp_files=1024kB' -c 'log_autovacuum_min_duration=1000ms' -c 'autovacuum_vacuum_cost_limit=200' -c 'bytea_output=escape' -c 'datestyle=iso,mdy' -c 'lc_messages=C' -c 'lc_monetary=C' -c 'lc_numeric=C' -c 'lc_time=C' -c 'max_locks_per_transaction=4096' -c 'standard_conforming_strings=on'"
        healthcheck:
          test: "psql -h localhost -U operator -d postgres -c '\\l'"
          interval: 30s
          timeout: 30s
          retries: 3
        deploy:
          placement:
            constraints: [engine.labels.os == linux]
          resources:
            reservations:
              cpus: '0.50'
              memory: 512M
# aip node
    aip-node:
        image: 172.31.66.14:5000/castsoftware/aip-node
        environment:
        - AIPNODE_DB_HOSTNAME=postgresql
        - AIPNODE_DB_PORT=5432
#Windows bind-mount volumes incompatible with Stacks and Services
#https://github.com/moby/moby/issues/39577
# The workaround is to remove the VOLUME directives in the dockerfile
        volumes:
        - type: bind 
          source: C:/CAST_AIP 
          target: C:/AIPFlat
          read_only: true
        - type: volume
          source: aip-node1
          target: C:/CASTMS
        deploy:
          placement:
            constraints: [engine.labels.os == windows]

    aip-nodeb:
        image: 172.31.66.14:5000/castsoftware/aip-node
        environment:
        - AIPNODE_DB_HOSTNAME=postgresql
        - AIPNODE_DB_PORT=5432
#Windows bind-mount volumes incompatible with Stacks and Services
#https://github.com/moby/moby/issues/39577
# The workaround is to remove the VOLUME directives in the dockerfile
        volumes:
        - type: bind 
          source: C:/CAST_AIP 
          target: C:/AIPFlat
          read_only: true
        - type: volume
          source: aip-node2
          target: C:/CASTMS
        deploy:
          placement:
            constraints: [engine.labels.os == windows]
 
# license: CAST_R&D:1;AIP/EFP:20200331:WZWHKHHQ
    aip-console:
        image: 172.31.66.15:5000/castsoftware/aip-console
        ports:
        - "8083:8081"
        volumes:
        - type: volume
          source: aip-console
          target: /aipconsole/data
        deploy:
          placement:
            constraints: [engine.labels.os == linux]

volumes:
  aip-console:
  aip-data:
  aip-node1:
  aip-node2: