postgresql_version: 10
postgresql_packages: ["postgresql-10", "postgresql-client-10", "libpq-dev"]
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_global_config_options:
    - { option: listen_addresses, value: "*" }

postgresql_hba_entries:
    - { type: local, database: all, user: postgres, auth_method: peer }
    - { type: local, database: all, user: all, auth_method: peer }
    - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
    - { type: host, database: all, user: all, address: '{{ subnet_cidr }}', auth_method: md5 }
