
---
# Fetches the aip zip from s3 - linux version
- name: Generate a s3 pre-fetch url to aip rest api installer
  vars:
      ansible_connection: local
  local_action:
      module: aws_s3
      bucket: "{{cast_aip_s3_bucket}}" 
      object: "{{cast_aip_console_zip}}"
      mode: geturl
  register: aip_console_s3_url

# Download the installer
- name: Download aip rest api installer
  get_url:
      url: "{{aip_console_s3_url.url}}"
      dest: "/tmp/AIP_CONSOLE.zip"

- name: Install unzip
  become: yes
  apt:
    name: unzip

- name: Unzip aip console release
  become: yes
  unarchive:
    src: /tmp/AIP_CONSOLE.zip
    dest: /tmp/
    remote_src: yes
