---
# Base CAIP Windows node
# This is used to bake a base Windows image to install the api on.
#
# often overridden variables:
# - cast_aip_install_dir: directory to install CAIP
# - cast_aip_s3_bucket: s3 bucket where release is stored
# - cast_aip_zip: release file name (also the s3 object key)


- name: Chocolatey
  win_chocolatey: name=chocolatey

- name: Disable enhanced exit codes.
  raw: Chocolatey feature disable -n useEnhancedExitCodes

- name: Install openjdk8
  win_chocolatey: name=adoptopenjdk8jre state=present

- name: Install 7zip
  win_chocolatey: name=7zip state=present

- name: Install nssm
  win_chocolatey: name=nssm

- name: Add java to path
  win_path:
      elements: 
        - 'C:\Program Files\AdoptOpenJDK\jdk8u202-b08-jre\bin'
        - 'C:\Program Files\7-zip'


# aws_s3 module cannot download on a windows host
# first get the s3 url then use win_get_url to download the content
- name: Get caip s3 url
  vars:
      ansible_connection: local
  local_action:
      module: aws_s3
      bucket: "{{cast_aip_s3_bucket}}" 
      object: "{{cast_aip_zip}}"
      mode: geturl
  register: caip_s3_url

- name: Download caip zip
  win_get_url:
      url: "{{caip_s3_url.url}}"
      dest: C:\CAST_AIP.zip


- name: Unzip CAIP
  win_command: '7z x C:\CAST_AIP.zip -oC:\CAST_AIP'
  args:
      chdir: C:\
      creates: C:\CAST_AIP\

- name : Copy custom setup fixture
  win_template:
      dest: C:\CAST_AIP\caip_silent_installation.iis
      src: 'caip_silent_installation.iis.j2'

- name: Install CAIP
  win_command: setup.bat /s /f1"C:\CAST_AIP\caip_silent_installation.iis" /f2"C:\CAST_AIP\caip_install.log"
  args:
      chdir: C:\CAST_AIP
      creates: "{{cast_aip_install_dir}}"

