# Filebeat 
- name: Install filebeat
  block:

    - name: Install filebeat docker stack for linux
      block:
      - name: Set docker filebeat docker stack file fact
        set_fact:
          docker_stack_filebeat_yml: /tmp/filebeat_stack.yml
      - name: Template for docker stack on linux
        template:
          src: linux_filebeat_stack.yml.j2
          dest: "{{docker_stack_filebeat_yml}}"
      when: 
      - ansible_os_family != "Windows"

    - name: Install filebeat docker stack for windows
      block:
      - name: Set docker filebeat docker stack file fact
        set_fact:
          docker_stack_filebeat_yml: C:\filebeat_stack.yml
      - name: Template for docker stack on Windows
        win_template:
          src: win_filebeat_stack.yml.j2
          dest: "{{docker_stack_filebeat_yml}}"
      when:
      - ansible_os_family == "Windows"

    - name: Start docker stack for filebeat
      docker_stack:
        state: present
        name: filebeat
        compose: 
        - "{{docker_stack_filebeat_yml}}"

  when: logcollector_host is defined
