---

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      validate_certs: no
      state: present

- name: Add postgresql repo for stretch
  apt_repository:
      repo:  deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main 
      state: present
      filename: pgdg.list

- name: Postgresql 
  import_role:
      name: geerlingguy.postgresql

- name: Postgres cast operator user
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_user:
      name: operator 
      password: CastAIP
      role_attr_flags: "SUPERUSER"

- name: Guest role
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_user:
    name: guest
    password: md5e80b4ebb3479aa8e36c37d5cc17a0141
    encrypted: yes 
    role_attr_flags: NOSUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE,NOREPLICATION


